# Generated by Django 3.2.12 on 2023-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airplane_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('economy_seats', models.IntegerField()),
                ('business_seats', models.IntegerField()),
                ('first_seats', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('basic_cost', models.FloatField()),
                ('fareperkm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='airplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('plane_id', models.CharField(max_length=100)),
                ('economy_price', models.IntegerField()),
                ('business_price', models.IntegerField()),
                ('first_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weeklyschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('plane_id', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('arrival_day', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
