# Generated by Django 3.2.12 on 2023-04-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentflight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('plane_id', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('b_as', models.IntegerField()),
                ('f_as', models.IntegerField()),
                ('e_as', models.IntegerField()),
                ('b_c', models.FloatField()),
                ('f_c', models.FloatField()),
                ('e_c', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='tickets',
            name='upi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
