# Generated by Django 3.2.12 on 2023-04-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20230407_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='distance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='truth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
