# Generated by Django 3.2.12 on 2023-04-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20230407_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelled_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('plane_id', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('booked_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('seat_type', models.CharField(max_length=100)),
                ('seat_no', models.IntegerField()),
                ('cost', models.FloatField()),
                ('upi', models.CharField(max_length=100)),
                ('truth', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='truth',
        ),
    ]
